### ISSUE TITLE
Complete README

### ISSUE THREAD

**Issue by iCodexDev** [RamiLego4Game/luajit-tdlib#3]
Hi,

Please Complete installation package and usage ways library and login on readme file.

Further details may be sufficient to use this library in Tdlib.

Thank You .

**Comment by Rami-Sabbagh** [comment]
Sorry I won't work on the project anymore due to lack of motivation and time

**Comment by Rami-Sabbagh** [comment]
In case if you want to fund the development of this project you can contact me at `ramilego4game@gmail.com`
